# -*- conf -*-
[mouse]
hide-when-typing=yes
[colors-dark]
background=171717
[main]
font=GohuFont11 Nerd Font Mono:size=8
font-bold=GohuFont11 Nerd Font Mono:size=8
font-italic=GohuFont11 Nerd Font Mono:size=8
dpi-aware=yes
[cursor]
style=underline
underline-thickness=2
blink=yes